# Generated by Django 3.0.8 on 2020-09-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='option',
            field=models.CharField(choices=[('Published', 'Publihsed'), ('Pending', 'Pending')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='trending',
            field=models.CharField(choices=[('New', 'New'), ('Hot', 'Hot')], max_length=100, null=True),
        ),
    ]
