# Generated by Django 3.0.8 on 2020-09-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_auto_20200929_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('Used', 'Used'), ('New', 'New')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='trending',
            field=models.CharField(choices=[('New', 'New'), ('Hot', 'Hot'), ('Normal', 'Normal')], default='Normal', max_length=100, null=True),
        ),
    ]
